"""
Auth APIs - session management, Xigncode flow, register, login

Real auth flow (confirmed from MITM captures v165):
  1. GET /auth/xcdSeed                     -> seed (no auth)
  2. Client generates Xigncode cookie with seed (device-specific, anti-cheat)
  3. GET /auth/xcd?cookie=<xigncode_cookie> -> accessToken stored on device
  4. POST /auth/login + accesstoken header  -> player state loaded

AES key v169.0.03: b53019bb76da6b34 (ECB, zeros pad, hex body)
POST body format: raw hex string, Content-Type: application/json
Auth header name: accesstoken (not Authorization: Bearer)

RegisterRequestModel fields (from IL2CPP dump.cs):
  type (int), id (Xigncode cookie), userName, castleName,
  kingPostfix (int), castlePostfix (int), version (int)

LoginRequestModel fields (from MITM capture):
  locale, platform, deviceInfo, version (str), cookie (Xigncode cookie)
"""
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from config import SESSION, set_auth_token, get, post, decode_response


def get_xigncode_seed() -> dict:
    """
    GET /auth/xcdSeed
    No auth required. Returns seed for client-side Xigncode cookie generation.
    Response: AuthResponseModel { seed: str, accessToken: null }
    """
    return get("/auth/xcdSeed")


def validate_xigncode(cookie: str) -> dict:
    """
    GET /auth/xcd?cookie=<xigncode_cookie>
    Validate Xigncode anti-cheat cookie. Returns accessToken on first device registration.
    Cookie format: '926988XXXX_<md5_fingerprint>_<md5_checksum>'
    Requires cookie generated by Xigncode SDK with the seed from get_xigncode_seed().
    """
    return get("/auth/xcd", params={"cookie": cookie})


def set_session_token(token: str):
    """
    Set the accesstoken header for all subsequent requests.
    Call after capturing a valid token from xcd or from the game's traffic.
    """
    SESSION.headers.update({"accesstoken": token})


def login(
    cookie: str,
    locale: str = "vi",
    platform: str = "IPhonePlayer",
    device_info: str = "iPhone13,3",
    version: str = "169.0.03",
) -> dict:
    """
    POST /auth/login
    Must have accesstoken header already set (from Xigncode xcd step).
    body: { locale, platform, deviceInfo, version, cookie }
    cookie: the Xigncode cookie string used in validate_xigncode()
    """
    body = {
        "locale": locale.upper(),
        "platform": platform,
        "deviceInfo": device_info,
        "version": version,
        "cookie": cookie,
    }
    return post("/auth/login", body)


def register(
    xigncode_cookie: str,
    user_name: str,
    castle_name: str,
    account_type: int = 0,
    king_postfix: int = 0,
    castle_postfix: int = 0,
    version: int = 169003,
) -> dict:
    """
    POST /auth/register
    Create new account. Requires accesstoken header set first (from xcd step).
    xigncode_cookie: the Xigncode cookie from validate_xigncode() - used as 'id' field
    account_type: 0=Guest (most common for new device)
    """
    return post("/auth/register", {
        "type": account_type,
        "id": xigncode_cookie,
        "userName": user_name,
        "castleName": castle_name,
        "kingPostfix": king_postfix,
        "castlePostfix": castle_postfix,
        "version": version,
    })


def shake_hand() -> dict:
    """POST /auth/shake-hand - heartbeat, keep session alive."""
    return post("/auth/shake-hand")


def check_patch_version(version: str) -> dict:
    """GET /auth/checkPatchVersion?version=<version>"""
    return get("/auth/checkPatchVersion", params={"version": version})


def get_patch_folder() -> dict:
    """
    POST /auth/getPatchFolder
    No auth required. Returns CDN patch folder URL.
    Response: PatchFolderResponseModel { folder: str }
    """
    return post("/auth/getPatchFolder", {})


def get_transfer_code() -> dict:
    """GET /auth/transfer/code - generate account transfer code (on old device)."""
    return get("/auth/transfer/code")


def transfer_account(code: str, account_type: int = 0) -> dict:
    """POST /auth/transfer - apply transfer code (on new device)."""
    return post("/auth/transfer", {"code": code, "type": account_type})


def link_account(code: str, account_type: int = 2) -> dict:
    """
    POST /auth/link - link guest account to platform account.
    account_type: 2=Google, 3=Apple
    """
    return post("/auth/link", {"code": code, "type": account_type})


def full_auth_flow(xigncode_cookie: str, locale: str = "vi", platform: str = "IPhonePlayer", device_info: str = "iPhone13,3") -> dict:
    """
    Helper: run full login flow once you have a Xigncode cookie.
    Returns the login response. accesstoken header is set in SESSION automatically.

    To get xigncode_cookie:
      1. seed_resp = get_xigncode_seed()
      2. generate cookie client-side with seed (requires Xigncode SDK or game binary)
      3. xcd_resp = validate_xigncode(cookie)  -> sets device registration

    OR: capture the cookie from game MITM proxy traffic.
    """
    xcd_resp = validate_xigncode(xigncode_cookie)
    if not xcd_resp.get("success"):
        raise RuntimeError(f"xcd validation failed: {xcd_resp}")

    # Token may come from xcd response or be pre-stored on device
    token = xcd_resp.get("accessToken")
    if token:
        set_session_token(token)

    return login(
        cookie=xigncode_cookie,
        locale=locale,
        platform=platform,
        device_info=device_info,
    )


if __name__ == "__main__":
    import json

    print("=== Get Xigncode Seed ===")
    try:
        result = get_xigncode_seed()
        print(f"seed[:80]: {result.get('seed', '')[:80]}")
        print(f"success: {result.get('success')}")
    except Exception as e:
        print(f"Error: {e}")

    print("\n=== Get Patch Folder ===")
    try:
        result = get_patch_folder()
        print(json.dumps(result, indent=2, ensure_ascii=False))
    except Exception as e:
        print(f"Error: {e}")
